import java.util.List;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ptang' at '8/8/15 1:02 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/8/15 1:02 PM
 */
public class Board {
    private List<String> cells;

    public Board(List<String> cells) {

        this.cells = cells;
    }


    public String produceBoard() {
        return "   |   |  \n" +
                "-----------\n" +
                "   |   |  \n" +
                "-----------\n" +
                "   |   |  \n";
    }

    public void mark(Integer location) {
        cells.set(location,"X");
    }
}
