import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static java.util.Arrays.asList;
import static org.hamcrest.core.Is.is;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ptang' at '8/8/15 1:02 PM' with Gradle 2.5
 *
 * @author ptang, @date 8/8/15 1:02 PM
 */
public class BoardTest {

    private static final Integer DEFAULT_LOCATION = 0;
    private Board board;
    private List<String> cells;

    @Before
    public void setUp() throws Exception {
        cells = new ArrayList<>(asList(" "," "," "," "," "," "," "," "," "));
        board = new Board(cells);
    }

    @Test
    public void shouldProduceBoardWhenRequested() {
        assertThat(board.produceBoard(), is(
                "   |   |  \n" +
                "-----------\n" +
                "   |   |  \n" +
                "-----------\n" +
                "   |   |  \n"));

    }

    @Test
    public void shouldMarkLocation0WithXWhenMarked() throws Exception {
        board.mark(DEFAULT_LOCATION);

        assertThat(cells.get(DEFAULT_LOCATION), is("X"));
    }

    @Test
    public void shouldMarkLocation1WithXWhenMarked() throws Exception {
        board.mark(1);

        assertThat(cells.get(1), is("X"));

    }
}
